### PR TITLE
Randomize prodSourceLabel in job_fetcher.  k8s: yaml load update

### PR DESCRIPTION
**Pull request by mightqxc**

### CODE REVIEW

**Comment by tmaeno** [comment]
Looks good. It is not very nice to have both worker_maker.pilotTypeRandomList and queue.prodSourceLabelRandomWeightsPermille configurable since they are essentially the same info. Is it possible to integrate them? e.g. using prodSourceLabelRandomWeightsPermille in the worker maker or setting worker_maker.pilotTypeRandomList in queue_config_mapper or something when queue.prodSourceLabelRandomWeightsPermille is used.

**Comment by mightqxc** [comment]
Actually in worker_maker, self.pilotTypeRandomList is not meant to be configurable (it will be overridden in the finally block after all); I just want it to be a private instance attribute to be called by other instance methods.

**Comment by tmaeno** [comment]
I meant worker_maker.pilotTypeRandomWeightsPermille instead of worker_maker.pilotTypeRandomList.

https://github.com/PanDAWMS/harvester_configurations/blob/master/GRID/common_grid_queueconfig_template.json#L185

which you mentioned looks very similar to prodSourceLabelRandomWeightsPermille in https://github.com/PanDAWMS/panda-harvester/wiki/Installation-and-configuration#queue-attributes

Essentially they define the info.

**Comment by mightqxc** [comment]
Yes, the information of prodsourcelabel and pilottype are very similar, yet I think not completely equivalent.

What has been done recently about pilot options of pilot1 and 2 requested by Paul --

All possibilities of options for Pilot 1:
    workspec.pilotType= RC: -u rc_test -i RC
    workspec.pilotType= ALRB: -u rc_alrb -i ALRB
    workspec.pilotType= PT: -u ptest -i PR
    workspec.pilotType= PR: -u managed/user -i PR

All possibilities of options for Pilot 2:
    workspec.pilotType= RC: -j rc_test2 -i RC --piloturl http://project-atlas-gmsb.web.cern.ch/project-atlas-gmsb/pilot2-dev.tar.gz
    workspec.pilotType= ALRB: -j rc_alrb -i ALRB
    workspec.pilotType= PT: -j ptest -i PR
    workspec.pilotType= PR: -j managed/user -i PR

One can see that for RC they want prodsourcelabel = rc_test for pilot 1 but rc_test2 for pilot 2 . This is a reason I have difficulty to merge the two randoms if we don't want to have different configs for pilot 1 and 2.
Also, the workspec.pilotType is not equivalent to the available option to pass to pilot (e.g. for ptest, Paul says pass "PR", not "PT"); this is covered in htcondor plugin.
Thus, it seems hard to have 1-1 mapping of workspec.pilotType (all possible combinations of pilot we want), prodsourcelabel, and pilottype for pilot option.

Maybe there is better solution?

**Comment by tmaeno** [comment]
It is not very good to absorb all pilot mess in harvester. For PT to PR conversion, it would have been better to ask Paul to change the pilot or wrapper so that it is converted outside of harvester. In any case, you need to use rc_test2 instead of rc_test for PUSH in queue.prodSourceLabelRandomWeightsPermille for pilot2 PQs. However, it is harmless to have both  rc_test and rc_test2 in the same PQ since one of them will just cause a few empty pilots or getJob requests. Basically combination of prodsoucelabel and pilot type is unique. How about something like  
```python
{("rc_test","RC"): {'version_tag':"RC", "weight": 10}, ("rc_test2","RC"): {"version_tag": "RC", "weight": 10}, ("rc_alrb","ALRB"): {"version_tag": "ALRB", "weight": 10}, ("ptest","PT"): {"version_tag": "PR", "weight": 10}}
```
When rc_test is chosen for a pilot2 PQ, the pilot or harvester will not get any job since there should not be jobs with prodsoucelabel=rc_test2. For PULL, empty pilots are waste of resources but it should be OK as long as the weight is small and will disappear once fully migrated to pilot2.

**Comment by mightqxc** [comment]
OK thanks. I will rewrite the code.

**Pull request closed without merging**
