### PR TITLE
use an rc_test prodsourcelabel 1% of job requests

### PR DESCRIPTION
**Pull request by davidgcameron**

### CODE REVIEW

**Comment by davidgcameron** [comment]
Yes, I agree hard-coding is not good, but it's also like this in SimpleWorkerMaker where the choice is made for pull mode.

What do you think about putting these parameters into panda_harvester.cfg? Since I don't think we need to set them per queue/template and this will make it easier to add any new label, eg

```[qconf]
prodSourceLabels =
 rc_test|1
 rc_alrb|1
 rc_test2|1
```

**Comment by tmaeno** [comment]
The list/weights can be PQ-dependent. e.g. you may want to run more alrb pilots at some PQ. It is possible to do something like

        "QUEUE_NAME": {
                "prodSourceLabel": "managed",
                ...
                 "newParam":{"rc_test": 1, "rc_test2":1, "rc_alrb": 1},

in queueconfig.json and then in job_fetcher you can get the dict through queueConfig.newParam.
It is enough to set the param in the template in queueconfig.json if we want to have some default for all PQs.

**Comment by mightqxc** [comment]
@davidgcameron @tmaeno :
Ratios in SimpleWorkerMaker are configurable in queue config like this
https://github.com/PanDAWMS/harvester_configurations/blob/master/GRID/common_grid_queueconfig_template.json#L185

So is anyone doing this for job_fecther now?
If not, I can do it to be configurable in queue config as SimpleWorkerMaker is.

**Comment by mightqxc** [comment]
I did it anyhow:
https://github.com/PanDAWMS/panda-harvester/pull/279
It is configurable in queue config with attribute `prodSourceLabelRandomWeightsPermille`
; documented here:
https://github.com/PanDAWMS/panda-harvester/wiki/Installation-and-configuration#queue-attributes

**Comment by tmaeno** [comment]
Done in https://github.com/PanDAWMS/panda-harvester/pull/280

**Pull request closed without merging**
